# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}
  APP_NAME : ${{ 'node-microservice-one' }}
  HEROKU_EMAIL : ${{ 'venu.shastri@gmail.com' }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
  deploy:
    name: Deploy to Heroku
    runs-on : ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Heroku Docker Container Deploy
      uses: lucassarcanjo/heroku-deploy@2.1.17
      with:
       # Email Linked to your Heroku Account
       email: $HEROKU_EMAIL
      # Heroku Dyno Formation
       formation: web
    # Your Heroku API Key
       api_key: $HEROKU_API_KEY
    # Your Heroku App Name
       app_name: $APP_NAME
    # Dokerfile path
       dockerfile_path: '.'
   
      
      
      
